NAME=usage-api
VERSION=latest
IMAGE_NAME=${DOCKER_HUB_USERNAME}/${NAME}
DOCKERFILE=Dockerfile

RELEASES_DIR_NAME=releases
RELEASES_DIR_REMOTE=/${RELEASES_DIR_NAME}
RELEASES_DIR_LOCAL=${PWD}/${RELEASES_DIR_NAME}
GOPATH_DIR=${PWD}/gopath

BUILD_USER=builder
CURRENT_USER_UID=1000
PORT=3000

default:
	make -C app release
	docker build -f ${DOCKERFILE} -t ${IMAGE_NAME}:${VERSION} .

run: default
	docker run --rm -ti -p ${PORT}:${PORT} -e IINET_USERNAME=${IINET_USERNAME} -e IINET_PASSWORD=${IINET_PASSWORD} -e VODAFONE_MOBILE_NUMBER=${VODAFONE_MOBILE_NUMBER} -e VODAFONE_PASSWORD=${VODAFONE_PASSWORD} ${IMAGE_NAME}:${VERSION}

daemon: default
	docker run -d -name ${NAME} -p ${PORT}:${PORT} -e IINET_USERNAME=${IINET_USERNAME} -e IINET_PASSWORD=${IINET_PASSWORD} -e VODAFONE_MOBILE_NUMBER=${VODAFONE_MOBILE_NUMBER} -e VODAFONE_PASSWORD=${VODAFONE_PASSWORD} ${IMAGE_NAME}:${VERSION}

push: default
	docker tag ${IMAGE_NAME}:latest ${DOCKER_REGISTRY}/${IMAGE_NAME}:latest && docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}:latest
