VERSION=latest
IMAGE_NAME=usage-api
DOCKERFILE=Dockerfile

BUILD_IMAGE_NAME=usage-api-build
BUILD_DOCKERFILE=Dockerfile.build

RELEASES_DIR_NAME=releases
RELEASES_DIR_REMOTE=/${RELEASES_DIR_NAME}
RELEASES_DIR_LOCAL=${PWD}/${RELEASES_DIR_NAME}
GOPATH_DIR=${PWD}/gopath

BUILD_USER=builder
CURRENT_USER_UID=1000

default:
	make -C app release
	docker build -f ${DOCKERFILE} -t ${IMAGE_NAME}:${VERSION} .

run: default
	docker run --rm -ti -e IINET_USERNAME=${IINET_USERNAME} -e IINET_PASSWORD:${IINET_PASSWORD} -e VODAFONE_MOBILE_NUMBER=${VODAFONE_MOBILE_NUMBER} -e VODAFONE_PASSWORD=${VODAFONE_PASSWORD} ${IMAGE_NAME}:${VERSION} bash
